Forked from ivan-kostko/go-sandbox
ivan-kostko/GoLibs pull request #25
Opened 2016-11-30 07:49 UTC by ivan-kostko

Forked starting from: https://github.com/ivan-kostko/go-sandbox/commit/c944b71c48e4dfe4a900dcf44a2c08ce6ca9e12d

2016-12-02 10:50 UTC, kobergj approved these changes
Looks awesome @ivan-kostko. Can't wait to work with it

2016-12-02 10:50 UTC, kobergj commented on WorkerPool/WorkerPool.go
> +	// for each initially empty slot we shoul put one value
typo: `should`

2016-12-02 10:50 UTC, kobergj commented on WorkerPool/WorkerPool_test.go
> +			// cancell workers
typo: `cancel`

2016-12-03 10:06 UTC, ivan-kostko commented
@kobergj pls CR fixes

2016-12-05 11:36 UTC, kobergj requested changes
неплохо @ivan-kostko, but please FOR my comments. (and fix typos!!)

2016-12-05 11:36 UTC, kobergj commented on WorkerPool/WorkerPool.go
> +	ERR_TIMEDOUTREQUSTSLOT = "The request for a free execution slot has been timed out"
I guess you mean `ERR_TIMEOUTREQUESTSLOT`, don't you?

2016-12-05 11:36 UTC, kobergj commented on WorkerPool/WorkerPool.go
> +	// Synchronously requests worker slot and end exectes/does WorkItem in parallel routine as soon as slot is obtained.
`and end executes`?

2016-12-05 11:36 UTC, kobergj commented on WorkerPool/WorkerPool.go
> +	// If no slot aquired upon timeOut exceeds - returns ERR_TIMEDOUTREQUSTSLOT.
Typos: `acquired` , `ERR_TIMEOUTREQUESTSLOT`

2016-12-05 11:36 UTC, kobergj commented on WorkerPool/WorkerPool.go
> +	// All requests waiting for slots should be notified and canceled returning ERR_WORKERPOOLSHUTDOWN.
typo: `cancelled`

2016-12-05 11:36 UTC, kobergj commented on WorkerPool/WorkerPool.go
> +func (this *workerPool) Do(wi WorkItem, timeOut time.Duration) error {
I think, due to consistency, we should also stick to CustomErrors here...

2016-12-05 11:36 UTC, kobergj commented on WorkerPool/WorkerPool_test.go
> +			// chanel workers are waiting for close
`chanel workers`? Isn't that a bit girly? I think `channel workers` would be a better name

2016-12-05 11:36 UTC, kobergj commented on WorkerPool/WorkerPool_test.go
> +		expectedDoneWorkers := testCase.ExpectedDonedWorkers
Is it `expectedDONEworkers` or `expectedDONEDworkers`?

2016-12-05 11:36 UTC, kobergj commented on WorkerPool/WorkerPool_test.go
> +					wg.Done()
Isn't it decrementing twice here? Once on the end of `Do` func and then again if no Error occured?

2016-12-05 11:36 UTC, kobergj commented on WorkerPool/WorkerPool_test.go
> +			ExpectedIsCancelationChanClosed: true,
typo `...cancellation...`

2016-12-05 11:36 UTC, kobergj commented on WorkerPool/WorkerPool_test.go
> +			// chanel workers are waiting for close
You really like `chanel`, right?

2016-12-05 11:36 UTC, kobergj commented on WorkerPool/WorkerPool_test.go
> +			// chanel closed on Close() complete
...

2016-12-05 11:36 UTC, kobergj commented on WorkerPool/WorkerPool_test.go
> +				actualIsCancelationChanClosed = true
Also: `...cancellation...`

2016-12-05 11:36 UTC, kobergj commented on WorkerPool/WorkerPool_test.go
> +				t.Errorf("For TestAlias '%s' WorkerPool.Close() with immidiate release of workers \r\n has CancelationChan Closed ( %v )  \r\n while expected %v \r\n", testAlias, actualIsCancelationChanClosed, e
typo? `immediate`? Also in other two `t.Errorf`

2016-12-05 11:36 UTC, kobergj commented on WorkerPool/WorkerPool_test.go
> +			// chanel workers are waiting for close
:expressionless:

2016-12-06 06:10 UTC, ivan-kostko commented on WorkerPool/WorkerPool_test.go
> +					wg.Done()
Not really. `wg.Done()` is invoked whether `func()` is executed, or if it is not and any error returned.

2016-12-06 06:12 UTC, ivan-kostko commented on WorkerPool/WorkerPool_test.go
> +					wg.Done()
To be 100%% clear, it should be wrapped into local anonymous function and `defer wg.Done()`. However, actually there is a bug in testing, which invokes `defer` in a very specific way.

2016-12-06 06:14 UTC, ivan-kostko commented on WorkerPool/WorkerPool.go
> +func (this *workerPool) Do(wi WorkItem, timeOut time.Duration) error {
CustomError implements `error` interface.

2016-12-07 06:15 UTC, merged